[book]
authors = ["Jonathan Johnson"]
language = "en"
multilingual = false
src = "src"
title = "Cushy User's Guide"

[build]
build-dir = "../target/guide"
extra-watch-dirs = ["./guide-examples/"]

[preprocessor.variables.variables]
docs = "https://docs.rs/cushy/latest/cushy"
src = "https://github.com/khonsulabs/cushy/tree/v0.3.0"
